name: PHP OOP - Latihan per Pertemuan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-pertemuan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dir: Pertemuan01
            entry: HelloWorld.php
          - dir: Pertemuan02
            entry: Main.php
          - dir: Pertemuan03
            entry: Main.php
          - dir: Pertemuan04
            entry: Main.php
          - dir: Pertemuan05
            entry: Main.php
          - dir: Pertemuan06
            entry: Main.php
          - dir: Pertemuan07
            entry: Main.php
          - dir: Pertemuan08
            skip: true
          - dir: Pertemuan09
            entry: Main.php
          - dir: Pertemuan10
            entry: Main.php
          - dir: Pertemuan11
            entry: Main.php
          - dir: Pertemuan12
            entry: Main.php
            # Input otomatis untuk menu:
            # 1 (tambah) → NIM → Nama
            # 1 (tambah) → NIM → Nama
            # 3 (tampil), lalu 0 (keluar)
            input: "1\n2310001\nAri\n1\n2310002\nNina\n3\n0\n"
          - dir: Pertemuan13
            entry: Main.php
          - dir: Pertemuan14
            entry: Main.php
          - dir: Pertemuan15
            entry: Main.php
          - dir: Pertemuan16
            entry: App.php

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          ini-values: |
            memory_limit=512M
            error_reporting=E_ALL
            display_errors=On

      - name: Resolve base dir
        id: basedir
        run: |
          if [ -d "php-oop-multifile" ]; then
            BD="php-oop-multifile"
          else
            BD="."
          fi
          echo "value=$BD" >> "$GITHUB_OUTPUT"
          echo "Using BASE_DIR=$BD"

      - name: Skip marker
        if: matrix.skip == 'true'
        run: echo "Skipping ${{ matrix.dir }} (no PHP files)"

      - name: List folder (debug)
        if: matrix.skip != 'true'
        run: |
          echo "Workspace root:"
          ls -la
          echo "Listing ${{ steps.basedir.outputs.value }}/${{ matrix.dir }}:"
          ls -la "${{ steps.basedir.outputs.value }}/${{ matrix.dir }}" || true

      - name: Run ${{ matrix.dir }} -> ${{ matrix.entry }} (with optional input)
        if: matrix.skip != 'true'
        shell: bash
        run: |
          set -e
          BASE="${{ steps.basedir.outputs.value }}"
          RUN_DIR="$BASE/${{ matrix.dir }}"
          ENTRY="${{ matrix.entry }}"
          if [ ! -d "$RUN_DIR" ]; then
            echo "Folder tidak ditemukan: $RUN_DIR"
            exit 2
          fi
          cd "$RUN_DIR"
          if [ ! -f "$ENTRY" ]; then
            echo "Entry file tidak ditemukan: $RUN_DIR/$ENTRY"
            ls -la
            exit 3
          fi

          # Jika matrix.input terisi, kirim ke STDIN; kalau tidak, jalankan biasa
          if [ -n "${{ matrix.input }}" ]; then
            printf "%b" "${{ matrix.input }}" | php "$ENTRY"
          else
            php "$ENTRY"
          fi

      - name: Upload output (opsional)
        if: always() && matrix.skip != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.dir }}
          path: |
            ${{ steps.basedir.outputs.value }}/${{ matrix.dir }}/output*.txt
          if-no-files-found: ignore
